// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '01-etudiants' }],
  entreprises: [{ type: 'autogenerated', dirName: '02-entreprises' }],
};

module.exports = sidebars;
